version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Testing...
      - npm test
      - echo Building...
      - npm run-script build
artifacts:
  files:
    - public/**/*
    - src/**/*
    - package.json
  discard-paths: no
  base-directory: dist
