version: 0.2

phases:
  install:
    commands:
      - echo Installing Node 12...
      - curl -fsSL https://deb.nodesource.com/setup_19.x | sudo -E bash - &&\
      - sudo apt-get install -y nodejs
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Testing...
      - npm test
      - echo Building...
      - npm run-script build
artifacts:
  files:
    - public/**/*
    - src/**/*
    - package.json
    - package-lock.json
